=== iakkus/knix/GUI/lib/knix-asl-validator/schemas/state-machine.json
{
  "$id": "http://knix-asl-validator.cloud/state-machine#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Comment": {
      "type": "string"
    },
    "StartAt": {
      "type": "string"
    },
    "EnableCheckpoints": {
        "enum": [true, false]
    },
    "AllowImmediateMessages": {
        "enum": [true, false]
    },
    "States": {
      "type": "object",
      "patternProperties": {
        "^.{1,128}$": {
          "$ref": "http://knix-asl-validator.cloud/state#"
        }
      },
      "additionalProperties": false
    },
    "Version": {
      "type": "string"
    },
    "TimeoutSeconds": {
      "type": "integer",
      "minimum": 0
    }
  },
  "additionalProperties": false,
  "required": ["StartAt", "States"]
}

=== iakkus/knix/tests/asl_KNIX_flags/wf_asl_session_all.json
{
  "Comment": "Session functions in KNIX",
  "StartAt": "entryFunction",
  "AllowImmediateMessages": true,
  "States": {
    "entryFunction": {
      "Type": "Task",
      "Resource": "entryFunction",
      "PotentialNext": ["sessionFunction1", "sessionFunction2", "finalFunction", "telemetryHandler"],
      "End": true
    },
    "heartbeatHandler": {
      "Type": "Task",
      "Resource": "heartbeatHandler",
      "PotentialNext": ["healthChecker"]
    },
    "telemetryHandler": {
      "Type": "Task",
      "Resource": "telemetryHandler",
      "PotentialNext": ["finalFunction"]
    },
    "sessionFunction1": {
      "Type": "Task",
      "Resource": "sessionFunction1",
      "SessionFunction": true,
      "SessionFunctionParameters": {
          "heartbeat_method": "function",
          "heartbeat_function": "heartbeatHandler",
          "heartbeat_interval_ms": 15000
      },
      "Next": "finalFunction",
      "PotentialNext": ["telemetryHandler"]
    },
    "sessionFunction2": {
      "Type": "Task",
      "Resource": "sessionFunction2",
      "SessionFunction": true,
      "SessionFunctionParameters": {
          "heartbeat_method": "function",
          "heartbeat_function": "heartbeatHandler",
          "heartbeat_interval_ms": 15000
      },
      "Next": "finalFunction",
      "PotentialNext": ["telemetryHandler"]
    },
    "finalFunction": {
      "Type": "Task",
      "Resource": "finalFunction",
      "End": true
    }
  }
}
